### ISSUE TITLE
Loading stuff when first opening the app can be slow

### ISSUE THREAD

**Issue by noah-someck** [ritvikkar/MovieFinder#37]
We need to make this loading faster or show that stuff is loading

**Comment by kevinchristianson** [comment]
if still true after fixing #39 then add loading image to fragment_movies_tv.xml and set it to animate in a circle forever. In setUpPager, kill the animation and set image visibility to invisible.

**Comment by kevinchristianson** [comment]
I added a loading screen to Movies and TV. I'll close this issue but we can reopen it or make a new one for actually trying to load items faster

**Comment by kevinchristianson** [comment]
@noah-someck mentioned that there could be improvements so I will re-open this do implement those:

- [ ] Have loading screens for each PageFragment rather than for each MediaFragment
- [ ] Check for internet connection in MediaFragment and show no-wifi symbol and error text if not available
- [ ] Have error text under loading screen and show exclamation point error symbol and error text if not able to load data
